image: Visual Studio 2017

before_build:
    - nuget restore Task1/Task1/Task1.sln

build_script:
    - dotnet build Task1/Task1/Task1.sln

test_script:
    - dotnet test Task1/Task1/Task1.sln