image: Visual Studio 2017

before_build:
    - nuget restore reTask2/rewritingWork_2.sln

build_script:
    - dotnet build reTask2/rewritingWork_2.sln

test_script:
    - dotnet test reTask2/rewritingWork_2.sln